export const GET_TREASURES = 'GET_TREASURES';
export const GET_SELECTEDTREASURE = 'GET_SELECTEDTREASURE';
export const GET_LOGINUSER = 'GET_LOGINUSER';
export const GET_LOGOUTUSER = 'GET_LOGOUTUSER';
export const TAKE_PICTURES = 'TAKE_PICTURES';
export const INITIAL_PICTURES = 'INITIAL_PICTURES';
